// Member API: login, D1 migration from KV, claims, profile, availability, votes, portal, roles (P0.3, P0.6).
import { call, env, login, mockDiscord, seal, siteJson, sqlite, W } from './mock.mjs';
import { t, done } from './lib.mjs';
import { can, permsFor } from '../bot/roles.js';

const boss = await login('111', [], 'Зуб_Ноrex 👑');
t('login returns a session', typeof boss === 'string');
t('KV → D1 migration ran once', /^done/.test(sqlite.prepare("SELECT value FROM meta WHERE key='kv_migrated'").get()?.value));
const n = (tb) => sqlite.prepare(`SELECT COUNT(*) n FROM ${tb}`).get().n;
t('users migrated + login upsert', n('users') === 2);
t('claims/profiles/availability/votes migrated', n('claims') === 1 && n('profiles') === 1 && n('availability') === 2 && n('votes') === 2);
t('UTF-8 name survives the session', (await call(boss, '/api/me')).d.user.name === 'Зуб_Ноrex 👑');

// login edge cases
mockDiscord.inGuild = false;
t('not in the Discord server → not_member', (await login('999')).error === 'not_member');
mockDiscord.inGuild = true;
const badState = await W('/auth/callback?code=x&state=forged');
t('forged OAuth state → 400', badState.status === 400);
const evil = await W('/auth/login?return=' + encodeURIComponent('https://evil.example/'));
t('login return URL limited to the site → 400', evil.status === 400);

const mike = await seal({ u: '222', n: 'Mike', a: 'x', adm: false });
const other = await seal({ u: '333', n: '<script>x</script>', a: 'y', adm: false });
t('no token → 401', (await call(null, '/api/me')).s === 401);
t('forged token → 401', (await call(mike.slice(0, -2) + 'aa', '/api/me')).s === 401);
t('expired token → 401', (await call(await seal({ u: '222', n: 'M', a: 'x', exp: 1 }), '/api/me')).s === 401);
let r = await call(mike, '/api/me');
t('me: migrated claim + profile', r.s === 200 && r.d.claim.status === 'pending' && Array.isArray(r.d.claim.history) && r.d.profile.positions[0] === 'CM');
t('member → portal 403', (await call(mike, '/api/admin/overview')).s === 403);
let ov = (await call(boss, '/api/admin/overview')).d;
t('overview shape', ov.users['222'].logins === 3 && ov.users['111'].admin === true && ov.claims['222'] && ov.activity.length >= 2 && ov.availability.length === 7 && ov.votes.length === 3);
t('approve claim', (await call(boss, '/api/admin/claims', { user: '222', action: 'approve' })).s === 200);
let pub = (await call(null, '/api/public')).d;
t('public cache rebuilt on approve', Object.values(pub.claims)[0]?.name === 'Mike' && Object.values(pub.claims)[0].platform === 'PS5');
t('claiming an owned player → 409', (await call(other, '/api/claim', { player: '1007531598629' })).s === 409);
const p2 = siteJson('players').find((x) => x.home && x.k !== '1007531598629');
r = await call(other, '/api/claim', { player: p2.k });
t('new claim pending', r.s === 200 && r.d.claim.status === 'pending' && r.d.claim.playerName === p2.n);
t('claim for a non-squad player → 400/404', [400, 404].includes((await call(other, '/api/claim', { player: 'nobody' })).s));
r = await call(other, '/api/claim', { cancel: true });
t('cancel claim', r.d.claim === null && !sqlite.prepare("SELECT 1 FROM claims WHERE user_id='333'").get());
r = await call(other, '/api/profile', { bio: 'hi <img src=x onerror=alert(1)>', positions: ['ST', 'XX'], platform: 'Nope' });
t('XSS: profile bio stripped, bad positions/platform dropped', !r.d.profile.bio.includes('<') && r.d.profile.positions.join() === 'ST' && r.d.profile.platform === '');
r = await call(other, '/api/profile', { bio: 'x'.repeat(5000) });
t('profile bio length capped', r.d.profile.bio.length <= 280);
const d = new Date().toISOString().slice(0, 10);
r = await call(other, '/api/availability', { dates: [d], status: 'maybe' });
t('availability set', r.d.days[0].people.length === 2 && r.d.days[0].people.some((p) => p.id === '333' && p.s === 'maybe'));
r = await call(other, '/api/availability', { dates: [d], status: 'clear' });
t('availability clear', r.d.days[0].people.length === 1);
t('availability in the past → 400', (await call(other, '/api/availability', { dates: ['1999-01-01'], status: 'yes' })).s === 400);
const m = (await call(other, '/api/vote')).d.matches[0];
r = await call(other, '/api/vote', { match: m.id, player: m.players[0].k });
t('MOTM vote', r.d.matches[0].total === 2 && r.d.matches[0].mine === m.players[0].k);
r = await call(other, '/api/vote', { match: m.id, player: m.players[0].k });
t('MOTM vote toggles off', r.d.matches[0].total === 1 && r.d.matches[0].mine === null);
t('vote for a player not in the match → 400', (await call(other, '/api/vote', { match: m.id, player: 'nobody' })).s === 400);
ov = (await call(boss, '/api/admin/claims', { user: '222', action: 'unlink' })).d;
t('unlink keeps history', ov.claims['222'].status === 'unlinked' && ov.claims['222'].history.map((h) => h.action).join() === 'approved,unlinked');
t('public cleared after unlink', Object.keys((await call(null, '/api/public')).d.claims).length === 0);
t('unknown claim → 404', (await call(boss, '/api/admin/claims', { user: 'nope', action: 'approve' })).s === 404);
t('unknown route → 404', (await call(boss, '/api/nope')).s === 404);
t('activity stores the XSS name as text (client escapes)', (await call(boss, '/api/admin/overview')).d.activity.every((a) => typeof a.n === 'string'));

// ---------- roles (P0.6) ----------
const role = async (tok) => (await call(tok, '/api/me')).d?.user;
let u = await role(boss);
t('ADMIN_IDS → owner, sees all messages', u.role === 'owner' && u.admin && u.perms.includes('messages.all') && u.roleLabel === 'Owner');
u = await role(await login('555', ['founder']));
t('Founder role → owner', u.role === 'owner' && u.perms.includes('settings.bot'));
const mgr = await login('444', ['mgr']);
u = await role(mgr);
t('manager role → manager, no private messages', u.role === 'manager' && u.admin && u.perms.includes('messages.reported') && !u.perms.includes('messages.all'));
t('manager opens the portal', (await call(mgr, '/api/admin/overview')).s === 200);
const plain = await login('666', ['random']);
u = await role(plain);
t('plain member', u.role === 'member' && !u.admin && !u.perms.includes('feedback.send') && u.perms.includes('vote.motm'));
t('member → decide claims 403', (await call(plain, '/api/admin/claims', { user: '222', action: 'approve' })).s === 403);
t('users.role stored', sqlite.prepare("SELECT role FROM users WHERE id='555'").get().role === 'owner' && sqlite.prepare("SELECT role FROM users WHERE id='444'").get().role === 'manager');
await call(boss, '/api/admin/claims', { user: '222', action: 'approve' });
u = await role(mike);
t('approved claim → claimed (no re-login)', u.role === 'claimed' && u.perms.includes('feedback.send') && !u.perms.includes('portal.view'));
await call(boss, '/api/admin/claims', { user: '222', action: 'unlink' });
t('unlinked → member again', (await role(mike)).role === 'member');
t('legacy adm session → manager', (await role(await seal({ u: '444', n: 'M', a: 'x', adm: true }))).role === 'manager');
t('legacy ADMIN_IDS session → owner', (await role(await seal({ u: '111', n: 'B', a: 'x', adm: true }))).role === 'owner');
t('tampered role in token → 401', (await call(mike.split('.')[0].slice(0, -4) + 'AAAA.' + mike.split('.')[1], '/api/me')).s === 401);
t('can(): guest blocked, unknown action throws', !can(null, 'hub.use') && !can({ role: 'guest' }, 'vote.motm') && (() => { try { can({ role: 'owner' }, 'nope'); return false; } catch { return true; } })());
t('tiers inherit', permsFor('owner').length > permsFor('manager').length && permsFor('manager').length > permsFor('claimed').length && permsFor('claimed').length > permsFor('member').length);
t('CORS only for the site origin', (await W('/api/public', { headers: { Origin: 'https://evil.example' } })).headers.get('access-control-allow-origin') !== 'https://evil.example');
t('not-member login not stored, no double migration', n('users') === 5 && !sqlite.prepare("SELECT 1 FROM users WHERE id='999'").get());
done();
