// Rush results (P0.4): members submit, managers confirm; public list only shows confirmed results.
import { call, KV, login, siteJson, W } from './mock.mjs';
import { t, done } from './lib.mjs';

const players = siteJson('players').filter((p) => p.home);
const clubs = siteJson('clubs');
const member = await login('500');
const mgr = await login('600', ['mgr']);
const other = await login('700');
const today = new Date().toISOString().slice(0, 10);
const base = { date: today, opponent: clubs[1].n.toUpperCase(), gf: 5, ga: 3, players: [{ k: players[0].k, pos: 'ST', g: 3, a: 1, r: 8.7, motm: true }, { k: players[1].k, pos: 'CM', g: 1, a: 2, r: '7.25' }, { n: 'Guest <b>Bob</b>', pos: 'CB', g: 0 }], shot: 'https://example.com/a.png', note: 'Great <script>' };
const publicList = async () => (await (await W('/api/rush')).json()).matches;

t('public GET /api/rush without login, empty', (await W('/api/rush')).status === 200 && (await publicList()).length === 0);
t('queue needs login', (await W('/api/rush/queue')).status === 401);
t('goals > score rejected', (await call(member, '/api/rush', { ...base, gf: 2 })).d.error?.includes('more than'));
t('future date rejected', (await call(member, '/api/rush', { ...base, date: '2099-01-01' })).s === 400);
t('no players rejected', (await call(member, '/api/rush', { ...base, players: [] })).s === 400);
t('non-squad key rejected', (await call(member, '/api/rush', { ...base, players: [{ k: 'nope' }] })).s === 400);
t('duplicate player rejected', (await call(member, '/api/rush', { ...base, players: [base.players[0], base.players[0]] })).s === 400);
t('two MOTM rejected', (await call(member, '/api/rush', { ...base, players: [{ ...base.players[0] }, { ...base.players[1], motm: true }] })).d.error?.includes('one man'));
t('XSS: javascript: screenshot URL rejected', (await call(member, '/api/rush', { ...base, shot: 'javascript:alert(1)' })).s === 400);
t('rating > 10 rejected', (await call(member, '/api/rush', { ...base, players: [{ ...base.players[0], r: 11 }] })).s === 400);
const sub = await call(member, '/api/rush', base);
t('member submit → pending', sub.s === 200 && sub.d.status === 'pending' && sub.d.mine.length === 1);
const m1 = sub.d.mine[0];
t('opponent matched to tracked club (case-insensitive)', m1.opp === clubs[1].n && m1.oppId === String(clubs[1].id));
t('XSS: HTML stripped from note and guest name', !m1.note.includes('<') && !m1.players[2].n.includes('<'));
t('rating rounded, guest has no key', m1.players[1].r === 7.3 && m1.players[2].k === undefined);
t('pending not public', (await publicList()).length === 0);
t('duplicate result → 409', (await call(member, '/api/rush', base)).s === 409);
t('member cannot confirm → 403', (await call(member, '/api/rush/decide', { id: m1.id, action: 'confirm' })).s === 403);
const q = await call(mgr, '/api/rush/queue');
t('manager sees pending queue', q.d.canConfirm && q.d.pending.length === 1);
t('member does not see others pending', (await call(member, '/api/rush/queue')).d.pending.length === 0);
const c = await call(mgr, '/api/rush/decide', { id: m1.id, action: 'confirm' });
t('manager confirms', c.s === 200 && c.d.pending.length === 0 && c.d.recent[0].status === 'confirmed');
const pub = await publicList();
t('confirmed is public, without submitter/status', pub.length === 1 && pub[0].res === 'W' && !pub[0].by && !pub[0].status);
t('double confirm → 409', (await call(mgr, '/api/rush/decide', { id: m1.id, action: 'confirm' })).s === 409);
const direct = await call(mgr, '/api/rush', { ...base, gf: 1, ga: 4, date: new Date(Date.now() - 864e5).toISOString().slice(0, 10), opponent: 'Random FC', players: [{ k: players[2].k, g: 1 }] });
t('manager log counts straight away', direct.d.status === 'confirmed' && (await publicList()).length === 2);
t('newest first', (await publicList())[0].date === today);
const s2 = await call(member, '/api/rush', { ...base, gf: 0, ga: 0, players: [{ k: players[0].k }] });
const id2 = s2.d.mine.find((x) => x.status === 'pending').id;
t("cannot withdraw someone else's → 403", (await call(other, '/api/rush/decide', { id: id2, action: 'withdraw' })).s === 403);
t('withdraw own pending', (await call(member, '/api/rush/decide', { id: id2, action: 'withdraw' })).d.mine.every((x) => x.id !== id2));
const s3 = await call(member, '/api/rush', { ...base, gf: 9, ga: 9, players: [{ k: players[0].k }] });
const id3 = s3.d.mine.find((x) => x.gf === 9).id;
t('manager rejects', (await call(mgr, '/api/rush/decide', { id: id3, action: 'reject' })).d.recent.some((x) => x.id === id3 && x.status === 'rejected'));
t('member sees rejection', (await call(member, '/api/rush/queue')).d.mine.find((x) => x.id === id3).status === 'rejected');
t('remove confirmed → gone from public', (await call(mgr, '/api/rush/decide', { id: direct.d.id, action: 'remove' })).s === 200 && (await publicList()).length === 1);
t('cannot remove a rejected one → 409', (await call(mgr, '/api/rush/decide', { id: id3, action: 'remove' })).s === 409);
let last;
for (let i = 0; i < 12; i++) last = await call(other, '/api/rush', { ...base, gf: 20 + i, ga: 0, players: [{ k: players[0].k }] });
t('rate limit 10/day → 429', last.s === 429);
const act = (await call(mgr, '/api/admin/overview')).d.activity;
t('activity logged', act.some((a) => a.type === 'rush-confirmed') && act.some((a) => a.type === 'rush-submit'));
t('KV cache in sync', JSON.parse((await KV.get('rush')) ?? '{}').matches?.length === 1);
done();
