// Lookbook: one page of proposed visual types, animations and transitions, all live, using the real club data. Visitors star the ones they like.
import { players, recent, clubStats as C, leaders, fmtDate } from '../lib/data.mjs';
import { card, esc } from '../lib/ui.mjs';
import { formations as FM } from './stats.mjs';

const top = players.filter((p) => p.ovr).sort((a, b) => b.ovr - a.ovr).slice(0, 12);
const six = top.slice(0, 6);
const q = players.filter((p) => p.gp >= 8);
const mx = (f) => Math.max(1e-9, ...q.map(f));
const AX = [['Goals / game', (p) => p.goals / p.gp], ['Assists / game', (p) => p.assists / p.gp], ['Rating', (p) => p.rating], ['Passing', (p) => p.pass], ['Tackling', (p) => p.tackleRate], ['Win rate', (p) => p.win]];
const radar = { axes: AX.map((a) => a[0]), series: q.sort((a, b) => b.rating - a.rating).slice(0, 3).map((p) => ({ n: p.n, v: AX.map(([, f]) => +(f(p) / mx(f)).toFixed(3)) })) };
const LB = { form: recent.map((m) => ({ opp: m.opp, gf: m.gf, ga: m.ga, res: m.res, d: fmtDate(m.t) })).reverse(), radar, race: Object.fromEntries([['goals', (p) => p.goals], ['assists', (p) => p.assists], ['rating', (p) => +p.rating.toFixed(1)], ['mom', (p) => p.mom]].map(([k, f]) => [k, (leaders[k] || []).slice(0, 6).map((p) => ({ n: p.n, v: f(p) }))])), club: { gp: C.gp, w: C.w, d: C.d, l: C.l, gf: C.gf, ga: C.ga, sr: C.sr, streak: C.streak }, players: six.map((p) => ({ n: p.n, ovr: p.ovr, g: p.goals, a: p.assists, r: +p.rating.toFixed(1), gp: p.gp, arch: p.arch, line: p.line, mom: p.mom, win: p.win })) };

const clubF = FM.formations.find((f) => f.main) || FM.formations[0];
const byLine = (l, k) => players.filter((x) => x.line === l && x.gp >= 5).sort((a, b) => b.gp - a.gp).slice(0, k);
const XI = [...byLine('GK', 1), ...byLine('DEF', clubF.rows[0].length), ...byLine('MID', clubF.rows.slice(1, -1).reduce((a, r) => a + r.length, 0)), ...byLine('FWD', clubF.rows.at(-1).length)];
LB.formation = clubF; LB.xi = XI.map((p) => ({ k: p.k, n: p.n, line: p.line, arch: p.arch, ovr: p.ovr }));
LB.walls = FM.formations.filter((f) => f.main).concat(FM.formations.filter((f) => !f.main).slice(0, 9)).map((f) => ({ id: f.id, rows: f.rows }));
const T = players.filter((x) => x.gp >= 8);
const best = (f) => T.slice().sort((a, b) => f(b) - f(a))[0];
const AW = [['Golden Boot', '⚽', best((x) => x.goals), (x) => x.goals + ' goals'], ['Playmaker', '🅰️', best((x) => x.assists), (x) => x.assists + ' assists'], ['Top rated', '⭐', best((x) => x.rating), (x) => x.rating.toFixed(1) + ' avg'], ['Man of the match', '🏅', best((x) => x.mom), (x) => x.mom + ' MOTM'], ['The Wall', '🧤', best((x) => x.cs), (x) => x.cs + ' clean sheets'], ['Iron man', '⏱️', best((x) => x.gp), (x) => x.gp + ' games']];
const tab = top.slice(0, 8);
const mxv = (f) => Math.max(1e-9, ...tab.map(f));
const heat = (v, m) => `background:rgba(200,53,44,${(0.08 + 0.5 * v / m).toFixed(2)})`;
const ICONS = { pitch: '<rect x="2" y="4" width="20" height="16" rx="1"/><path d="M12 4v16"/><circle cx="12" cy="12" r="3"/>', boot: '<path d="M3 5h6l1 6 8 2c2 .5 3 2 3 4v1H3z"/><path d="M6 17v2M10 17v2M14 17v2"/>', glove: '<path d="M7 21v-6L4 9a1.5 1.5 0 0 1 3-1l1 2V4a1.5 1.5 0 0 1 3 0v5V3a1.5 1.5 0 0 1 3 0v6V5a1.5 1.5 0 0 1 3 0v10l-2 6z"/>', whistle: '<circle cx="8" cy="15" r="5"/><path d="M12 11l9-3v5l-5 1"/><circle cx="8" cy="15" r="1.5"/>', trophy: '<path d="M7 4h10v5a5 5 0 0 1-10 0z"/><path d="M7 6H4c0 3 1 5 3 5M17 6h3c0 3-1 5-3 5M12 14v4M8 21h8M9 18h6"/>', flag: '<path d="M5 21V3M5 4h13l-3 4 3 4H5"/>', shield: '<path d="M12 3l8 3v6c0 5-4 8-8 9-4-1-8-4-8-9V6z"/>', key: '<circle cx="8" cy="12" r="4"/><path d="M12 12h9M18 12v4M21 12v3"/>', locker: '<rect x="4" y="3" width="16" height="18" rx="1"/><path d="M12 3v18M9 10v2M15 10v2"/>', card: '<rect x="5" y="3" width="14" height="18" rx="2"/><circle cx="12" cy="10" r="3"/><path d="M8 17h8"/>', star: '<path d="M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1L3.2 9.5l6.1-.9z"/>', stopwatch: '<circle cx="12" cy="14" r="7"/><path d="M12 14V9M9 3h6M18 6l1.5-1.5"/>' };
const cup = (id, label, val, dim) => `<div class="cab${dim ? ' dim' : ''}"><svg viewBox="0 0 100 120" class="cup" aria-hidden="true"><defs><linearGradient id="cg${id}" x1="0" x2="1"><stop offset="0" stop-color="#a77a22"/><stop offset=".45" stop-color="#fff1c2"/><stop offset="1" stop-color="#c9993a"/></linearGradient><clipPath id="cc${id}"><path d="M25 10h50v30c0 20-12 32-25 34-13-2-25-14-25-34z"/><rect x="45" y="74" width="10" height="18"/><rect x="30" y="92" width="40" height="10" rx="3"/><rect x="24" y="102" width="52" height="12" rx="3"/></clipPath></defs><path d="M25 18H10c0 18 8 28 18 30M75 18h15c0 18-8 28-18 30" fill="none" stroke="url(#cg${id})" stroke-width="5" stroke-linecap="round"/><g fill="url(#cg${id})"><path d="M25 10h50v30c0 20-12 32-25 34-13-2-25-14-25-34z"/><rect x="45" y="74" width="10" height="18"/><rect x="30" y="92" width="40" height="10" rx="3"/><rect x="24" y="102" width="52" height="12" rx="3"/></g><g clip-path="url(#cc${id})"><rect class="shine" x="-40" y="0" width="30" height="130" fill="#fff" opacity=".55" transform="skewX(-20)"/></g></svg><b>${val}</b><u>${label}</u></div>`;
let N = 0;
const opt = (id, title, desc, demo, o = {}) => `<article class="opt${o.wide ? ' wide' : ''}" id="${id}" data-id="${id}" data-name="${esc(title)}"><header><span class="no">${String(++N).padStart(2, '0')}</span><div><h3>${title}</h3>${o.top ? '<span class="rec">Recommended</span>' : ''}</div><button class="pick" type="button" aria-pressed="false">☆ I like this</button></header><p>${desc}</p><div class="demo">${demo}</div></article>`;
const sec = (id, ico, t, sub, body) => `<section class="lsec" id="${id}"><div class="lh"><span class="ico">${ico}</span><div><h2>${t}</h2><p>${sub}</p></div></div><div class="grid">${body}</div></section>`;

const sections = [
  sec('look', '🎨', 'The look', 'Brighter background and richer card surfaces. Both switch live across this whole page, so click around.', [
    opt('bg', 'Brighter backgrounds', 'Three directions: a vivid crest red, a lifted charcoal that is softer than pure black, and a clean white. Click one and the whole page changes.', `<div class="sw" data-set="theme"><button data-v="crest"><i style="background:linear-gradient(135deg,#8f2620,#d94438)"></i>Bright crest red</button><button data-v="char" class="on"><i style="background:linear-gradient(135deg,#25282e,#434955)"></i>Dimmed black</button><button data-v="chalk"><i style="background:linear-gradient(135deg,#ffffff,#e4e7ef)"></i>Chalk white</button></div>`, { wide: true, top: true }),
    opt('fin', 'Glossy card finishes', 'Darker, glassier cards on a lighter canvas, so the cards read as polished objects instead of flat dull panels. Pick a finish.', `<div class="sw" data-set="fin"><button data-v="gloss" class="on"><i class="fn-gloss"></i>Gloss black</button><button data-v="smoked"><i class="fn-smoked"></i>Smoked glass</button><button data-v="lacquer"><i class="fn-lacq"></i>Red lacquer</button><button data-v="matte"><i class="fn-matte"></i>Matte</button></div>`, { wide: true, top: true }),
    opt('pat', 'Card surface patterns', 'Every panel can carry a subtle pattern so it stands out from the background. Pick one and every card on the page changes.', `<div class="sw" data-set="pat"><button data-v="wing" class="on"><i class="p-wing"></i>Wing stripes</button><button data-v="hex"><i class="p-hex"></i>Hex mesh</button><button data-v="pitch"><i class="p-pitch"></i>Pitch lines</button><button data-v="kit"><i class="p-kit"></i>Kit pinstripe</button><button data-v="crest"><i class="p-crest"></i>Crest watermark</button><button data-v="none"><i></i>Plain</button></div>`, { wide: true, top: true }),
  ].join('')),

  sec('nav', '🧭', 'Menus that follow you', 'Scroll down: the top bar tucks away and your chosen style takes over. Switch style here and keep scrolling to feel it.', [
    opt('nav-orb', 'Gold orb with a fan menu', 'Once you scroll, the bar shrinks into a glowing crest orb. Tap it and the choices fan out in an arc with a spring.', `<button class="btn" data-nav="orb">Try it on this page</button>`, { top: true }),
    opt('nav-island', 'Dynamic island pill', 'A floating pill that shows where you are and a progress bar. Tap and it stretches open into the full menu.', `<button class="btn" data-nav="island">Try it on this page</button>`),
    opt('nav-rail', 'Side rail with labels', 'A slim rail of dots down the edge with a progress line. Hover (or tap) and the labels slide out.', `<button class="btn" data-nav="rail">Try it on this page</button>`),
  ].join('')),

  sec('views', '🎴', 'Rails, reels and richer views', 'More to see per page without it feeling crowded: swipe sideways, flip, stack, spin.', [
    opt('v-cover', '3D player coverflow', 'Swipe or scroll sideways: the card in the middle faces you, the rest turn away in depth. Real player cards.', `<div class="rail cover" id="cover">${top.map((p) => `<div class="ci">${card(p, { s: .9, link: false })}</div>`).join('')}</div>`, { wide: true, top: true }),
    opt('v-film', 'Match film strip', 'Results as tape frames you swipe along. Each frame lifts and shows the score, opposition and date.', `<div class="rail film" id="film">${LB.form.slice().reverse().map((m) => `<div class="fr ${m.res}"><i class="perf"></i><div class="d">${m.d}</div><div class="sc"><b>${m.gf}</b>–<b>${m.ga}</b></div><div class="o">${esc(m.opp)}</div><span class="r">${m.res}</span><i class="perf b"></i></div>`).join('')}</div>`, { wide: true, top: true }),
    opt('v-time', 'Session timeline reel', 'A glowing line of games in date order. Drag along it; each dot opens its result with a pop.', `<div class="rail tl" id="tl"><div class="line"></div>${LB.form.map((m, i) => `<button class="dot ${m.res}" style="--i:${i}" data-i="${i}"><span class="pt"></span><span class="lbl">${m.d}</span></button>`).join('')}</div><div class="tlo" id="tlo">Tap a game</div>`, { wide: true }),
    opt('v-deck', 'Swipe deck', 'A stack of player cards. Tap the top one and it flicks away to the back of the pile.', `<div class="deck" id="deck">${six.map((p) => `<div class="dk">${card(p, { s: .95, link: false })}</div>`).join('')}</div><p class="hint">Tap the top card</p>`),
    opt('v-flip', 'Flip card with a stat back', 'Tap a card: it spins and shows the player\'s season on the reverse. Same gold frame on both sides.', `<div class="flipwrap">${six.slice(0, 3).map((p, i) => `<button class="flip" type="button"><span class="f"><span class="ft">${card(p, { s: .8, link: false })}</span><span class="bk"><b>${esc(p.n)}</b><em>${esc(p.arch)}</em><i><u>${p.goals}</u>Goals</i><i><u>${p.assists}</u>Assists</i><i><u>${p.rating.toFixed(1)}</u>Rating</i><i><u>${p.mom}</u>MOTM</i></span></span></button>`).join('')}</div>`),
    opt('v-radar', 'Animated radar compare', 'Three top-rated players drawn as shapes that grow out from the middle. Hover a name to isolate them.', `<div id="radar" class="radar"></div>`),
    opt('v-tower', '3D stat towers', 'Goal leaders as towers on a turning stage, with the numbers floating above each one.', `<div class="stage3"><div class="towers" id="towers">${(LB.race.goals || []).map((r, i) => `<div class="tw" style="--h:${Math.max(18, (r.v / Math.max(1, LB.race.goals[0].v)) * 130)}px;--i:${i}"><span class="top"><b>${r.v}</b>${esc(r.n.length > 9 ? r.n.slice(0, 8) + '…' : r.n)}</span><i class="f1"></i><i class="f2"></i><i class="f3"></i></div>`).join('')}</div></div>`),
    opt('v-form', 'Form orbs and goal wave', 'Last ten games as glowing orbs plus a wave of goal difference that draws itself on screen.', `<div class="formrow" id="formrow"></div><svg class="wave" id="wave" viewBox="0 0 600 120" preserveAspectRatio="none"></svg>`),
    opt('v-race', 'Leaderboard race', 'Switch between goals, assists, rating and MOTM and the bars race to their new lengths.', `<div class="chips" id="racetabs"><button class="chip on" data-k="goals">Goals</button><button class="chip" data-k="assists">Assists</button><button class="chip" data-k="rating">Rating</button><button class="chip" data-k="mom">MOTM</button></div><div class="race" id="race"></div>`),
    opt('v-bento', 'Bento dashboard', 'A mosaic of tiles of different sizes, each with a live number, a mini chart or a ring. One look and you have the whole club.', `<div class="bento" id="bento"><div class="tile big"><u>Skill rating</u><b class="cnt" data-n="${C.sr}">0</b><svg viewBox="0 0 100 24" preserveAspectRatio="none"><path d="M0 20 L14 17 L28 18 L42 11 L56 13 L70 6 L84 8 L100 2" class="spark"/></svg></div><div class="tile"><u>Played</u><b class="cnt" data-n="${C.gp}">0</b></div><div class="tile"><u>Goals</u><b class="cnt" data-n="${C.gf}">0</b></div><div class="tile ring"><svg viewBox="0 0 80 80"><circle cx="40" cy="40" r="32"/><circle cx="40" cy="40" r="32" class="v" style="--p:${C.w / C.gp}"/></svg><b>${Math.round(C.w / C.gp * 100)}%</b><u>Win rate</u></div><div class="tile"><u>Conceded</u><b class="cnt" data-n="${C.ga}">0</b></div><div class="tile gold"><u>Win streak</u><b class="cnt" data-n="${C.streak}">0</b></div></div>`, { wide: true }),
    opt('v-flipnum', 'Scoreboard flip digits', 'Numbers that roll like a stadium scoreboard when they come into view.', `<div class="flips" id="flips"></div>`),
  ].join('')),


  sec('pitch', '🏟️', 'Pitch designs', 'The pitch is the heart of Tactics. Real proportions and markings, your usual XI, and four ways it can look. Tap a player marker to pop their card.', [
    opt('p-fin', 'Pitch finishes', 'The same pitch in four finishes. Pick one and every pitch below changes.', `<div class="sw" data-set="pstyle"><button data-v="grass" class="on"><i class="pf-grass"></i>Striped grass</button><button data-v="night"><i class="pf-night"></i>Floodlit night</button><button data-v="blue"><i class="pf-blue"></i>Blueprint</button><button data-v="chalk"><i class="pf-chalk"></i>Chalkboard</button></div>`, { wide: true, top: true }),
    opt('p-3d', '3D broadcast pitch', 'The pitch tilts back like a TV camera and the players stand up on it. Real 105 × 68 m markings, your usual lineup.', `<div class="pbox" id="p3d"></div><div id="ppop" class="ppop"></div>`, { wide: true, top: true }),
    opt('p-flat', 'Flat tactical board', 'Straight from above with names and roles. Clean, exact, the view for planning set pieces.', `<div class="pbox" id="pflat"></div>`, { wide: true }),
    opt('p-port', 'Portrait pitch for phones', 'Same real pitch turned upright so it fills a phone, with every marker, label and arrow turned with it.', `<div class="pbox" id="pport"></div>`),
    opt('p-rush', 'Rush 5v5 pitch', 'The smaller Rush pitch with its own box proportions and the Defensive 3-1 and Offensive 2-2 shapes from your diagrams.', `<div class="pbox" id="prush"></div><div class="chips" id="rushsw"><button class="chip on" data-s="3-1">Defensive 3-1</button><button class="chip" data-s="2-2">Offensive 2-2</button></div>`),
    opt('p-wall', 'Formation wall', 'Every shape as a mini diagram you can scan at a glance. Hover to light one up, tap to see its slots.', `<div class="fwall" id="fwall"></div>`, { wide: true, top: true }),
  ].join('')),

  sec('tables', '📊', 'Table designs', 'Tables that stay readable but feel designed: ranks, bars, heat, podiums and expandable rows. All from your real player stats.', [
    opt('tb-glass', 'Leaderboard table with bars', 'Rank medals, the player chip, an in-row bar for the main stat and a rating pill. Rows glow on hover.', `<div class="tbl glass">${tab.map((x, i) => `<div class="tr" style="--i:${i}"><span class="rk r${i + 1}">${i + 1}</span><span class="nm"><b>${esc(x.n)}</b><em>${esc(x.arch)} · ${x.line}</em></span><span class="bar"><i style="--w:${(x.goals / mxv((y) => y.goals) * 100).toFixed(0)}%"></i></span><b class="v">${x.goals}</b><span class="pill2">${x.rating.toFixed(1)}</span></div>`).join('')}</div>`, { wide: true, top: true }),
    opt('tb-heat', 'Heat-shaded stat grid', 'Every cell tinted by how strong the number is, with a sticky header and name column so wide tables scroll sideways comfortably.', `<div class="hscroll"><table class="heat"><thead><tr><th>Player</th><th>GP</th><th>Goals</th><th>Assists</th><th>Rating</th><th>MOTM</th><th>Pass %</th><th>Win %</th></tr></thead><tbody>${tab.map((x) => `<tr><th>${esc(x.n)}</th><td style="${heat(x.gp, mxv((y) => y.gp))}">${x.gp}</td><td style="${heat(x.goals, mxv((y) => y.goals))}">${x.goals}</td><td style="${heat(x.assists, mxv((y) => y.assists))}">${x.assists}</td><td style="${heat(x.rating, 10)}">${x.rating.toFixed(1)}</td><td style="${heat(x.mom, mxv((y) => y.mom))}">${x.mom}</td><td style="${heat(x.pass, 100)}">${x.pass}</td><td style="${heat(x.win, 100)}">${x.win}</td></tr>`).join('')}</tbody></table></div>`, { wide: true, top: true }),
    opt('tb-pod', '3D podium + list', 'The top three stand on a podium in 3D, everyone else in a tidy list under it.', `<div class="podium">${[1, 0, 2].map((i) => { const x = tab[i]; return `<div class="pd p${i + 1}"><div class="who"><b>${esc(x.n.length > 11 ? x.n.slice(0, 10) + '…' : x.n)}</b><em>${x.goals} goals</em></div><div class="blk"><span>${i + 1}</span></div></div>`; }).join('')}</div><div class="tbl glass mini">${tab.slice(3, 7).map((x, i) => `<div class="tr"><span class="rk">${i + 4}</span><span class="nm"><b>${esc(x.n)}</b></span><b class="v">${x.goals}</b></div>`).join('')}</div>`),
    opt('tb-exp', 'Expandable rows', 'Tap a row and it opens a strip with the player\'s season split, instead of sending you to another page.', `<div class="tbl xp">${tab.slice(0, 5).map((x) => `<div class="xr"><button class="tr"><span class="nm"><b>${esc(x.n)}</b><em>${esc(x.arch)}</em></span><b class="v">${x.ovr}</b><i class="chev">⌄</i></button><div class="xd"><div><u>Goals</u><b>${x.goals}</b></div><div><u>Assists</u><b>${x.assists}</b></div><div><u>Rating</u><b>${x.rating.toFixed(1)}</b></div><div><u>MOTM</u><b>${x.mom}</b></div><div><u>Win %</u><b>${x.win}</b></div></div></div>`).join('')}</div>`),
    opt('tb-res', 'Results ledger', 'Each game as a striped row: coloured edge for the result, score in a pill, opponent and date. Quick to scan top to bottom.', `<div class="tbl led">${LB.form.slice().reverse().map((m) => `<div class="tr ${m.res}"><span class="dt">${m.d}</span><span class="nm"><b>${esc(m.opp)}</b></span><span class="sc2">${m.gf}–${m.ga}</span><span class="rs">${m.res}</span></div>`).join('')}</div>`, { wide: true }),
  ].join('')),

  sec('trophy', '🏆', 'Trophies, badges and icons', 'Award and achievement visuals, plus a custom icon set that could replace emoji everywhere. All numbers are your real ones.', [
    opt('tr-cab', 'Trophy cabinet', 'Gold cups with a light that sweeps across them. Each stands for something the club has actually done.', `<div class="cabinet">${cup('a', 'Division', 'Div ' + (C.div || 1), 0)}${cup('b', 'Win streak', C.streak, 0)}${cup('c', 'Goals scored', C.gf, 0)}${cup('d', 'Promotions', C.promotions ?? 0, 0)}${cup('e', 'Skill rating', C.sr, 0)}${cup('f', 'Next: Elite division', '?', 1)}</div>`, { wide: true, top: true }),
    opt('tr-med', 'Award medals', 'Medal emblems for the season awards, each with the real current leader underneath.', `<div class="medals">${AW.map(([t, ic, x, f], i) => `<div class="md" style="--i:${i}"><svg viewBox="0 0 80 100"><path d="M22 0l14 38h8L58 0z" fill="#c8352c"/><path d="M30 0l9 26 9-26z" fill="#fff" opacity=".85"/><circle cx="40" cy="64" r="28" fill="url(#mg)" stroke="#fff1c2" stroke-width="2"/><circle cx="40" cy="64" r="21" fill="none" stroke="#7a5614" stroke-width="1.5" stroke-dasharray="2 3"/><text x="40" y="73" text-anchor="middle" font-size="24">${ic}</text></svg><b>${t}</b><em>${esc(x.n)}</em><u>${f(x)}</u></div>`).join('')}<svg width="0" height="0"><defs><radialGradient id="mg" cx=".35" cy=".3"><stop offset="0" stop-color="#fff1c2"/><stop offset=".6" stop-color="#e0b04a"/><stop offset="1" stop-color="#8a6212"/></radialGradient></defs></svg></div>`, { wide: true, top: true }),
    opt('tr-icons', 'Custom icon set', 'Twelve football icons in one line style, replacing emoji so everything feels like one family. They wiggle and glow on hover.', `<div class="icons">${Object.entries(ICONS).map(([k, d]) => `<button class="ic" title="${k}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${d}</svg><span>${k}</span></button>`).join('')}</div>`, { wide: true }),
    opt('tr-potm', 'Player of the month poster', 'A spotlight poster for the top performer: rays of light, their gold card and the stat line. Used on Home and in Hall of Fame.', `<div class="poster"><div class="rays"></div><div class="pt"><span>PLAYER OF THE MONTH</span>${card(best((x) => x.rating), { s: 1, link: false })}<b>${esc(best((x) => x.rating).n)}</b><em>${best((x) => x.rating).rating.toFixed(1)} average · ${best((x) => x.rating).goals} goals · ${best((x) => x.rating).assists} assists</em></div></div>`),
    opt('tr-tier', 'Rank tier emblems', 'Shield emblems that level up from Bronze to Elite, with a number in the middle. Could show form, streaks or level.', `<div class="tiers">${[['Bronze', '#b0703c', '#5a3416'], ['Silver', '#cfd6e2', '#5e6779'], ['Gold', '#efcf7a', '#8a6212'], ['Elite', '#6ee7ff', '#1b5a74']].map(([n, a, b], i) => `<div class="tr2" style="--i:${i}"><svg viewBox="0 0 60 70"><defs><linearGradient id="t${i}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><path d="M30 3l24 8v22c0 17-11 28-24 33C17 61 6 50 6 33V11z" fill="url(#t${i})" stroke="#fff" stroke-opacity=".5" stroke-width="1.5"/><text x="30" y="42" text-anchor="middle" font-family="Oswald" font-weight="700" font-size="24" fill="#fff" style="paint-order:stroke" stroke="rgba(0,0,0,.35)" stroke-width="2">${i + 1}</text></svg><b>${n}</b></div>`).join('')}</div>`),
  ].join('')),

  sec('trans', '🎬', 'Page changes, reloads and transitions', 'Press play and the whole screen performs it, exactly how a page change would feel. Every click on the real site could use one of these.', [
    opt('t-curtain', 'Red and gold curtain', 'A crest-red curtain with a gold edge sweeps across, then pulls away to the next page.', `<button class="btn play" data-t="curtain">▶ Play</button>`, { top: true }),
    opt('t-iris', 'Crest iris', 'A circle opens from where you tapped, with the crest in the centre, and swallows the page.', `<button class="btn play" data-t="iris">▶ Play</button>`),
    opt('t-shutter', 'Shutter blinds', 'Ten vertical blinds close in a wave and then open in the opposite wave.', `<button class="btn play" data-t="shutter">▶ Play</button>`),
    opt('t-zoom', 'Card zoom', 'The thing you tapped grows to fill the screen and becomes the next page. Great for card to profile.', `<button class="btn play" data-t="zoom">▶ Play</button>`, { top: true }),
    opt('t-lines', 'Pitch lines draw', 'Pitch markings draw themselves on a dark screen, then the page appears inside them.', `<button class="btn play" data-t="lines">▶ Play</button>`),
    opt('t-doors', 'Locker doors', 'Two gold doors close then open outward. The Hub entrance in short form, for other sections.', `<button class="btn play" data-t="doors">▶ Play</button>`),
    opt('t-load', 'Reload intro', 'What a reload looks like: the crest pulses, a gold line fills, the content rises in with a stagger.', `<button class="btn play" data-t="load">▶ Play</button>`),
  ].join('')),

  sec('micro', '✨', 'Clicks, hovers and little moments', 'Small things that make the site feel alive. Try each pad.', [
    opt('m-burst', 'Click burst', 'Every click throws a quick spray of gold, red and white sparks from the cursor.', `<div class="pad" id="burst">Click anywhere in here</div>`, { top: true }),
    opt('m-mag', 'Magnetic buttons', 'Buttons lean toward your cursor and spring back, with a glow that follows.', `<div class="padrow" id="mag"><button class="btn">Join</button><button class="btn gold">Apply</button><button class="btn">Squad</button></div>`),
    opt('m-spot', 'Spotlight hover', 'A soft light follows your cursor over the card surface and lights the pattern underneath.', `<div class="spots" id="spots"><div class="sp"><b>Squad</b><span>${players.length} players</span></div><div class="sp"><b>Results</b><span>${C.gp} games</span></div><div class="sp"><b>Leaders</b><span>top 6</span></div></div>`, { top: true }),
    opt('m-ripple', 'Ripple buttons', 'A ring spreads out from exactly where you pressed.', `<div class="padrow"><button class="btn rip">Press me</button><button class="btn gold rip">Press me</button></div>`),
    opt('m-trail', 'Cursor trail', 'A fading comet of light follows the pointer on pitch and chalkboard pages.', `<div class="pad" id="trail">Move your pointer in here</div>`),
    opt('m-scr', 'Text scramble', 'Names resolve letter by letter when you hover. Good for leaderboards and awards.', `<div class="scr" id="scr">${six.slice(0, 4).map((p) => `<button class="scrb" data-t="${esc(p.n)}">${esc(p.n)}</button>`).join('')}</div>`),
    opt('m-tilt', 'Tilt and reflection', 'Cards tilt toward the cursor with a light sheen that slides across. Already on the site; shown here for comparison.', `<div class="padrow tiltrow">${six.slice(0, 3).map((p) => card(p, { s: .8, link: false })).join('')}</div>`),
  ].join('')),
];

const nav = [['look', 'Look'], ['nav', 'Menus'], ['views', 'Views'], ['pitch', 'Pitches'], ['tables', 'Tables'], ['trophy', 'Trophies'], ['trans', 'Transitions'], ['micro', 'Micro'], ['picks', 'My picks']];
export default function (P) {
  P('lookbook.html', `<!doctype html><html lang="en" data-theme="char" data-pat="wing" data-fin="gloss" data-pstyle="grass" data-nav="orb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lookbook · NOREX UNITED</title><link rel="icon" href="crest.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Oswald:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="tactics.css"><link rel="stylesheet" href="lookbook.css"></head><body class="lbody">
<div class="glow g1"></div><div class="glow g2"></div>
<header class="lbbar" id="lbbar"><a class="brand" href="index.html"><img src="crest.png" alt=""><b>NOREX</b> UNITED</a><nav>${nav.map(([i, t]) => `<a href="#${i}">${t}</a>`).join('')}</nav><span class="cnt2" id="pickcount">☆ 0 picked</span></header>
<main class="lwrap"><div class="intro"><span class="eyebrow">Design lookbook</span><h1>Pick what feels right</h1><p>${N || 40} proposals, all live and using your real club data. Star the 3–5 you like most (☆ I like this) and your list collects at the bottom. Nothing here is final: it is a menu to choose from.</p><div class="chips"><a class="chip gold" href="#look">Start: the look ↓</a><a class="chip" href="#picks">Jump to my picks</a></div></div>
${sections.join('')}
<section class="lsec" id="picks"><div class="lh"><span class="ico">⭐</span><div><h2>My picks</h2><p>Your starred proposals. Copy the list and send it back to me.</p></div></div><div class="panel picks" id="picklist"><p class="muted">Nothing starred yet.</p></div><div class="chips"><button class="btn gold" id="copyp">Copy my list</button><button class="btn" id="clearp">Clear</button><span class="muted small" id="copied"></span></div></section></main>
<div id="orb" class="navx orb"><button class="ob" aria-label="Menu" aria-expanded="false"><img src="crest.png" alt=""></button><div class="fan">${nav.map(([i, t], k) => `<a href="#${i}" style="--k:${k}">${t}</a>`).join('')}</div></div>
<div id="island" class="navx island"><button class="ib" aria-expanded="false"><span class="cur" id="icur">Look</span><i class="bar"><u id="ibar"></u></i></button><div class="il">${nav.map(([i, t]) => `<a href="#${i}">${t}</a>`).join('')}</div></div>
<div id="rail" class="navx rail">${nav.map(([i, t]) => `<a href="#${i}" data-s="${i}"><i></i><span>${t}</span></a>`).join('')}<u id="rbar"></u></div>
<div id="tov" aria-hidden="true"></div>
<div class="tray" id="tray"><span id="traytxt">☆ 0 picked</span><a class="btn gold" href="#picks">See my list</a></div>
<script>window.LB=${JSON.stringify(LB)};</script><script src="pitch.js"></script><script src="lookbook.js"></script></body></html>`);
}
