// Shared visual builders (picked from the lookbook). Each returns HTML wrapped in .wx; static/widgets.js brings them to life.
import { players, clubStats as C, leaders, recent, fmtDate } from './data.mjs';
import { card, esc, slug, chip } from './ui.mjs';

const wx = (cls, inner, attrs = '') => `<div class="wx ${cls}" ${attrs}>${inner}</div>`;
const J = (o) => esc(JSON.stringify(o));
export const byOvr = players.filter((p) => p.ovr).sort((a, b) => b.ovr - a.ovr);
const T = players.filter((p) => p.gp >= 8);
const best = (f) => T.slice().sort((a, b) => f(b) - f(a))[0];

// ---- icon set (replaces emoji) ----
import { ICON, ic } from './icons.mjs';
export { ICON, ic };
export const iconSheet = () => wx('', `<div class="icons">${Object.entries(ICON).map(([k, d]) => `<button class="ic" type="button" title="${k}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${d}</svg><span>${k}</span></button>`).join('')}</div>`);

// ---- bento + digits ----
export const bento = () => wx('', `<div class="bento"><div class="tile big"><u>Skill rating</u><b class="cnt" data-n="${C.sr}">0</b><svg viewBox="0 0 100 24" preserveAspectRatio="none"><path d="M0 20 L14 17 L28 18 L42 11 L56 13 L70 6 L84 8 L100 2" class="spark"/></svg></div><div class="tile"><u>Played</u><b class="cnt" data-n="${C.gp}">0</b></div><div class="tile"><u>Goals</u><b class="cnt" data-n="${C.gf}">0</b></div><div class="tile ring"><svg viewBox="0 0 80 80"><circle cx="40" cy="40" r="32"/><circle cx="40" cy="40" r="32" class="v" style="--p:${C.w / C.gp}"/></svg><b>${Math.round(C.w / C.gp * 100)}%</b><u>Win rate</u></div><div class="tile"><u>Conceded</u><b class="cnt" data-n="${C.ga}">0</b></div><div class="tile gold" style="grid-column:span 2"><u>Win streak</u><b class="cnt" data-n="${C.streak}">0</b></div><div class="tile" style="grid-column:span 2"><u>Goal difference</u><b class="cnt" data-n="${C.gf - C.ga}">0</b></div></div>`);
export const digits = (items = [['Played', C.gp], ['Won', C.w], ['Goals', C.gf], ['Skill rating', C.sr]]) => wx('', `<div class="flips" data-w="digits">${items.map(([l, v]) => `<div class="fl"><div class="fd" data-v="${v}">${String(v).split('').map(() => `<div class="dg"><span>${[0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map((n) => `<i>${n}</i>`).join('')}</span></div>`).join('')}</div><u>${l}</u></div>`).join('')}</div>`);

// ---- towers / race / radar / form ----
export const towers = (arr = leaders.goals, key = 'goals', unit = '') => { const rows = arr.slice(0, 6), mx = Math.max(1, rows[0]?.[key] ?? 1); return wx('', `<div class="stage3"><div class="towers">${rows.map((p, i) => `<a class="tw" href="player-${slug(p.k)}.html" style="--h:${Math.max(18, (p[key] / mx) * 130)}px;--i:${i}"><span class="top"><b>${typeof p[key] === 'number' && p[key] % 1 ? p[key].toFixed(1) : p[key]}${unit}</b>${esc(p.n.length > 9 ? p.n.slice(0, 8) + '…' : p.n)}</span><i class="f1"></i><i class="f2"></i><i class="f3"></i></a>`).join('')}</div></div>`); };
export const race = () => { const data = { goals: leaders.goals, assists: leaders.assists, rating: leaders.rating, mom: leaders.mom }; const R = Object.fromEntries(Object.entries(data).map(([k, a]) => [k, a.slice(0, 6).map((p) => ({ n: p.n, v: k === 'rating' ? +p.rating.toFixed(1) : p[k] }))])); return wx('', `<div class="chips" data-w="racetabs"><button class="chip on" data-k="goals">Goals</button><button class="chip" data-k="assists">Assists</button><button class="chip" data-k="rating">Rating</button><button class="chip" data-k="mom">MOTM</button></div><div class="race" data-w="race" data-j="${J(R)}"></div>`); };
const AX = [['Goals / game', (p) => p.goals / Math.max(1, p.gp)], ['Assists / game', (p) => p.assists / Math.max(1, p.gp)], ['Rating', (p) => p.rating], ['Passing', (p) => p.pass], ['Tackling', (p) => p.tackleRate], ['Win rate', (p) => p.win]];
export const radar = (list = T.slice().sort((a, b) => b.rating - a.rating).slice(0, 3)) => { const mx = AX.map(([, f]) => Math.max(1e-9, ...T.map(f))); return wx('', `<div class="radar" data-w="radar" data-j="${J({ axes: AX.map((a) => a[0]), series: list.map((p) => ({ n: p.n, v: AX.map(([, f], i) => +(f(p) / mx[i]).toFixed(3)) })) })}"></div>`); };
export const formWave = (ms = recent) => wx('', `<div data-w="form" data-j="${J(ms.map((m) => ({ opp: m.opp, gf: m.gf, ga: m.ga, res: m.res, d: fmtDate(m.t), id: m.id })).reverse())}"><div class="formrow"></div><svg class="wave" viewBox="0 0 600 120" preserveAspectRatio="none"></svg></div>`);

// ---- rails ----
export const coverflow = (list = byOvr.slice(0, 12)) => wx('', `<div class="rail cover" data-w="cover">${list.map((p) => `<div class="ci">${card(p, { s: .9 })}</div>`).join('')}</div>`);
export const deck = (list = byOvr.slice(0, 6)) => wx('', `<div class="deck" data-w="deck">${list.map((p) => `<div class="dk">${card(p, { s: .95, link: false })}</div>`).join('')}</div><p class="hint">Tap the top card</p>`);
export const flipcards = (list = byOvr.slice(0, 3)) => wx('', `<div class="flipwrap">${list.map((p) => `<button class="flip" type="button" aria-label="Flip ${esc(p.n)}"><span class="f"><span class="ft">${card(p, { s: .8, link: false })}</span><span class="bk"><b>${esc(p.n)}</b><em>${esc(p.arch)}</em><i><u>${p.goals}</u>Goals</i><i><u>${p.assists}</u>Assists</i><i><u>${p.rating.toFixed(1)}</u>Rating</i><i><u>${p.mom}</u>MOTM</i></span></span></button>`).join('')}</div>`);
export const timeline = (ms = recent) => wx('', `<div class="rail tl" data-w="tl"><div class="line"></div>${ms.slice().reverse().map((m, i) => `<button class="dot ${m.res}" data-i="${i}" data-h="match-${m.id}.html" data-t="${esc(`${fmtDate(m.t)} · ${m.gf}–${m.ga} vs ${m.opp}`)}"><span class="pt"></span><span class="lbl">${esc(m.opp.length > 11 ? m.opp.slice(0, 10) + '…' : m.opp)}<small>${fmtDate(m.t)}</small></span></button>`).join('')}</div><a class="tlo" id="tlo" href="results.html">Tap a game</a>`);

// ---- tables ----
const mxv = (arr, f) => Math.max(1e-9, ...arr.map(f));
export const glassTable = (arr, key, fmt = (v) => v, sub = (p) => `${p.arch} · ${p.line}`) => { const m = mxv(arr, (p) => p[key]); return wx('', `<div class="tbl glass">${arr.map((p, i) => `<a class="tr" href="player-${slug(p.k)}.html" style="--i:${i}"><span class="rk r${i + 1}">${i + 1}</span><span class="nm"><b>${esc(p.n)}</b><em>${esc(sub(p))}</em></span><span class="bar"><i style="--w:${(p[key] / m * 100).toFixed(0)}%"></i></span><b class="v">${fmt(p[key])}</b><span class="pill2">${p.rating ? p.rating.toFixed(1) : '—'}</span></a>`).join('')}</div>`); };
const heat = (v, m) => `background:rgba(200,53,44,${(0.08 + 0.5 * v / m).toFixed(2)})`;
export const heatTable = (arr) => wx('', `<div class="hscroll"><table class="heat"><thead><tr><th>Player</th><th>GP</th><th>Goals</th><th>Assists</th><th>Rating</th><th>MOTM</th><th>Pass %</th><th>Win %</th></tr></thead><tbody>${arr.map((p) => `<tr><th><a href="player-${slug(p.k)}.html">${esc(p.n)}</a></th><td style="${heat(p.gp, mxv(arr, (x) => x.gp))}">${p.gp}</td><td style="${heat(p.goals, mxv(arr, (x) => x.goals))}">${p.goals}</td><td style="${heat(p.assists, mxv(arr, (x) => x.assists))}">${p.assists}</td><td style="${heat(p.rating, 10)}">${p.rating.toFixed(1)}</td><td style="${heat(p.mom, mxv(arr, (x) => x.mom))}">${p.mom}</td><td style="${heat(p.pass, 100)}">${p.pass}</td><td style="${heat(p.win, 100)}">${p.win}</td></tr>`).join('')}</tbody></table></div>`);
export const podium = (arr, key, lab = 'goals', mini = true) => wx('', `<div class="podium">${[1, 0, 2].map((i) => { const x = arr[i]; return x ? `<a class="pd p${i + 1}" href="player-${slug(x.k)}.html"><div class="who"><b>${esc(x.n.length > 11 ? x.n.slice(0, 10) + '…' : x.n)}</b><em>${typeof x[key] === 'number' && x[key] % 1 ? x[key].toFixed(1) : x[key]} ${lab}</em></div><div class="blk"><span>${i + 1}</span></div></a>` : ''; }).join('')}</div>${!mini ? '' : `<div class="tbl glass mini">${arr.slice(3, 8).map((x, i) => `<a class="tr" href="player-${slug(x.k)}.html"><span class="rk">${i + 4}</span><span class="nm"><b>${esc(x.n)}</b></span><b class="v">${typeof x[key] === 'number' && x[key] % 1 ? x[key].toFixed(1) : x[key]}</b></a>`).join('')}</div>`}`);
export const expRows = (arr) => wx('', `<div class="tbl xp">${arr.map((x) => `<div class="xr"><button class="tr" type="button"><span class="nm"><b>${esc(x.n)}</b><em>${esc(x.arch)} · ${x.line}</em></span><b class="v">${x.ovr ?? '—'}</b><i class="chev">⌄</i></button><div class="xd"><div><u>Goals</u><b>${x.goals}</b></div><div><u>Assists</u><b>${x.assists}</b></div><div><u>Rating</u><b>${x.rating.toFixed(1)}</b></div><div><u>MOTM</u><b>${x.mom}</b></div><div><u>Win %</u><b>${x.win}</b></div><a class="chip gold" href="player-${slug(x.k)}.html" style="grid-column:1/-1;justify-self:center">Open profile →</a></div></div>`).join('')}</div>`);
export const ledger = (ms = recent) => wx('', `<div class="tbl led">${ms.map((m) => `<a class="tr ${m.res}" href="match-${m.id}.html"><span class="dt">${fmtDate(m.t)}</span><span class="nm"><b>${esc(m.opp)}</b></span><span class="sc2">${m.gf}–${m.ga}</span><span class="rs">${m.res}</span></a>`).join('')}</div>`);

// ---- trophies ----
let cupN = 0;
const cup = (label, val, dim) => { const id = 'c' + ++cupN; return `<div class="cab${dim ? ' dim' : ''}"><svg viewBox="0 0 100 120" class="cup" aria-hidden="true"><defs><linearGradient id="cg${id}" x1="0" x2="1"><stop offset="0" stop-color="#a77a22"/><stop offset=".45" stop-color="#fff1c2"/><stop offset="1" stop-color="#c9993a"/></linearGradient><clipPath id="cc${id}"><path d="M25 10h50v30c0 20-12 32-25 34-13-2-25-14-25-34z"/><rect x="45" y="74" width="10" height="18"/><rect x="30" y="92" width="40" height="10" rx="3"/><rect x="24" y="102" width="52" height="12" rx="3"/></clipPath></defs><path d="M25 18H10c0 18 8 28 18 30M75 18h15c0 18-8 28-18 30" fill="none" stroke="url(#cg${id})" stroke-width="5" stroke-linecap="round"/><g fill="url(#cg${id})"><path d="M25 10h50v30c0 20-12 32-25 34-13-2-25-14-25-34z"/><rect x="45" y="74" width="10" height="18"/><rect x="30" y="92" width="40" height="10" rx="3"/><rect x="24" y="102" width="52" height="12" rx="3"/></g><g clip-path="url(#cc${id})"><rect class="shine" x="-40" y="0" width="30" height="130" fill="#fff" opacity=".55" transform="skewX(-20)"/></g></svg><b>${val}</b><u>${label}</u></div>`; };
export const cabinet = () => wx('', `<div class="cabinet">${cup('Division', 'Div ' + (C.div || 1))}${cup('Win streak', C.streak)}${cup('Goals scored', C.gf)}${cup('Promotions', C.promotions ?? 0)}${cup('Skill rating', C.sr)}${cup('Next: Elite division', '?', 1)}</div>`);
export const AW = () => [['Golden Boot', '⚽', best((x) => x.goals), (x) => x.goals + ' goals'], ['Playmaker', '🅰️', best((x) => x.assists), (x) => x.assists + ' assists'], ['Top rated', '⭐', best((x) => x.rating), (x) => x.rating.toFixed(1) + ' avg'], ['Man of the match', '🏅', best((x) => x.mom), (x) => x.mom + ' MOTM'], ['The Wall', '🧤', best((x) => x.cs), (x) => x.cs + ' clean sheets'], ['Iron man', '⏱️', best((x) => x.gp), (x) => x.gp + ' games']];
export const medals = () => wx('', `<div class="medals">${AW().map(([t, i, x, f], k) => `<a class="md" href="player-${slug(x.k)}.html" style="--i:${k}"><svg viewBox="0 0 80 100"><path d="M22 0l14 38h8L58 0z" fill="#c8352c"/><path d="M30 0l9 26 9-26z" fill="#fff" opacity=".85"/><circle cx="40" cy="64" r="28" fill="url(#mg)" stroke="#fff1c2" stroke-width="2"/><circle cx="40" cy="64" r="21" fill="none" stroke="#7a5614" stroke-width="1.5" stroke-dasharray="2 3"/><text x="40" y="73" text-anchor="middle" font-size="24">${i}</text></svg><b>${t}</b><em>${esc(x.n)}</em><u>${f(x)}</u></a>`).join('')}<svg width="0" height="0"><defs><radialGradient id="mg" cx=".35" cy=".3"><stop offset="0" stop-color="#fff1c2"/><stop offset=".6" stop-color="#e0b04a"/><stop offset="1" stop-color="#8a6212"/></radialGradient></defs></svg></div>`);
export const poster = (p = best((x) => x.rating)) => wx('', `<div class="poster"><div class="rays"></div><div class="pt"><span>PLAYER OF THE MONTH</span>${card(p, { s: .78 })}<b>${esc(p.n)}</b><em>${p.rating.toFixed(1)} average · ${p.goals} goals · ${p.assists} assists</em></div></div>`);
export const tiers = (lvl = -1) => wx('', `<div class="tiers">${[['Bronze', '#b0703c', '#5a3416'], ['Silver', '#cfd6e2', '#5e6779'], ['Gold', '#efcf7a', '#8a6212'], ['Elite', '#6ee7ff', '#1b5a74']].map(([n, a, b], i) => `<div class="tr2${lvl >= 0 && i !== lvl ? ' off' : ''}" style="--i:${i}"><svg viewBox="0 0 60 70"><defs><linearGradient id="t${i}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><path d="M30 3l24 8v22c0 17-11 28-24 33C17 61 6 50 6 33V11z" fill="url(#t${i})" stroke="#fff" stroke-opacity=".5" stroke-width="1.5"/><text x="30" y="42" text-anchor="middle" font-family="Oswald" font-weight="700" font-size="24" fill="#fff" stroke="rgba(0,0,0,.35)" stroke-width="2" style="paint-order:stroke">${i + 1}</text></svg><b>${n}</b></div>`).join('')}</div>`);
// rating tier from card overall: <75 bronze, <80 silver, <85 gold, else elite
export const tierOf = (ovr) => (ovr >= 85 ? 3 : ovr >= 80 ? 2 : ovr >= 75 ? 1 : 0);
