// Shared visual builders (picked from the lookbook). Each returns HTML wrapped in .wx; static/widgets.js brings them to life.
import { players, clubStats as C, leaders, recent, matches, records, fmtDate } from './data.mjs';
import { card, esc, slug, chip, oppCrest, tagChips } from './ui.mjs';

const wx = (cls, inner, attrs = '') => `<div class="wx ${cls}" ${attrs}>${inner}</div>`;
const J = (o) => esc(JSON.stringify(o));
export const byOvr = players.filter((p) => p.ovr).sort((a, b) => b.ovr - a.ovr);
const T = players.filter((p) => p.gp >= 8);
const best = (f) => T.slice().sort((a, b) => f(b) - f(a))[0];

// ---- icon set (replaces emoji) ----
import { ICON, ic } from './icons.mjs';
export { ICON, ic };
export const iconSheet = () => wx('', `<div class="icons">${Object.entries(ICON).map(([k, d]) => `<button class="ic" type="button" title="${k}"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">${d}</svg><span>${k}</span></button>`).join('')}</div>`);

// ---- bento + digits ----
const pf = (v, d = 1) => (Math.round(v * 10 ** d) / 10 ** d).toFixed(d);
const pointsTrend = (n = 24) => { const ms = matches.slice(0, n).reverse(); let s = 0; return ms.map((m) => (s += m.res === 'W' ? 3 : m.res === 'D' ? 1 : 0)); };
export const bestRun = () => { let b = 0, c = 0; for (const m of matches.slice().reverse()) { c = m.res === 'W' ? c + 1 : 0; b = Math.max(b, c); } return b; };
export const runNow = () => { const r = matches[0]?.res; if (!r) return ['—', '']; let n = 0; for (const m of matches) { if (m.res === r) n++; else break; } return [n, { W: 'wins in a row', D: 'draws in a row', L: 'defeats in a row' }[r]]; };
const sparkPath = (v) => { const mx = Math.max(...v), mn = Math.min(...v), d = Math.max(1, mx - mn); const pts = v.map((y, i) => [(i / Math.max(1, v.length - 1)) * 100, 22 - ((y - mn) / d) * 20]); return { line: 'M' + pts.map((p) => p.map((n) => n.toFixed(1)).join(' ')).join(' L'), end: pts[pts.length - 1] }; };
export const bento = () => {
  const gdv = C.gf - C.ga, pg = (v) => pf(v / Math.max(1, C.gp)), sh = matches.filter((m) => m.ga === 0).length, [rn, rl] = runNow(), tr = pointsTrend(), sp = sparkPath(tr), wr = Math.round(C.w / Math.max(1, C.gp) * 100);
  const sub = (t) => `<small>${t}</small>`;
  return wx('', `<div class="bento">
<div class="tile big"><u>Skill rating</u><b class="cnt" data-n="${C.sr}">0</b>${sub(`Division ${C.div || 1} · ${C.promotions ?? 0} promotion${C.promotions === 1 ? '' : 's'} · ${C.pts ?? 0} pts`)}<svg viewBox="0 0 100 24" preserveAspectRatio="none" aria-hidden="true"><path d="${sp.line}" class="spark"/><circle cx="${sp.end[0].toFixed(1)}" cy="${sp.end[1].toFixed(1)}" r="1.6" class="sdot"/></svg><i class="cap">League points over the last ${tr.length} games</i></div>
<div class="tile"><u>Played</u><b class="cnt" data-n="${C.gp}">0</b>${sub(`<span class="gw">${C.w}W</span> · <span class="gd">${C.d}D</span> · <span class="gl">${C.l}L</span>`)}</div>
<div class="tile"><u>Goals scored</u><b class="cnt" data-n="${C.gf}">0</b>${sub(`${pg(C.gf)} per game`)}</div>
<div class="tile ring"><svg viewBox="0 0 80 80" aria-hidden="true"><circle cx="40" cy="40" r="32"/><circle cx="40" cy="40" r="32" class="v" style="--p:${C.w / Math.max(1, C.gp)}"/></svg><b>${wr}%</b><u>Win rate</u>${sub(`${C.w} of ${C.gp}`)}</div>
<div class="tile"><u>Goals conceded</u><b class="cnt" data-n="${C.ga}">0</b>${sub(`${pg(C.ga)} per game · ${sh} clean sheet${sh === 1 ? '' : 's'} in last ${matches.length}`)}</div>
<div class="tile gold wide"><u>Current run</u><b class="cnt" data-n="${typeof rn === 'number' ? rn : 0}">0</b>${sub(`${rl}${C.streak ? '' : ''} · unbeaten ${C.unbeaten ?? 0}`)}</div>
<div class="tile wide"><u>Goal difference</u><b class="cnt" data-n="${gdv}" data-sign="1">0</b>${sub(`${gdv >= 0 ? '+' : ''}${pg(gdv)} per game · ${C.gf} for, ${C.ga} against`)}</div>
</div><p class="wnote">Live from EA's club data · updated ${esc(fmtDate(Math.floor(Date.parse(C.fetched) / 1000)))} · ${C.gp} league games</p>`);
};
export const digits = (items = [['Played', C.gp, 'league games'], ['Won', C.w, `${Math.round(C.w / Math.max(1, C.gp) * 100)}% win rate`], ['Goals', C.gf, `${(C.gf / Math.max(1, C.gp)).toFixed(1)} per game`], ['Skill rating', C.sr, `Division ${C.div || 1}`]]) => wx('', `<div class="flips" data-w="digits">${items.map(([l, v, s]) => `<div class="fl"><div class="fd" data-v="${v}">${String(v).split('').map(() => `<div class="dg"><span>${[0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map((n) => `<i>${n}</i>`).join('')}</span></div>`).join('')}</div><u>${l}</u>${s ? `<small>${esc(s)}</small>` : ''}</div>`).join('')}</div>`);

// ---- towers / race / radar / form ----
export const towers = (arr = leaders.goals, key = 'goals', unit = '') => { const rows = arr.slice(0, 6), mx = Math.max(1, rows[0]?.[key] ?? 1); return wx('', `<div class="stage3"><div class="towers">${rows.map((p, i) => `<a class="tw" href="player-${slug(p.k)}.html" style="--h:${Math.max(18, (p[key] / mx) * 130)}px;--i:${i}"><span class="top"><b>${typeof p[key] === 'number' && p[key] % 1 ? p[key].toFixed(1) : p[key]}${unit}</b>${esc(p.n.length > 9 ? p.n.slice(0, 8) + '…' : p.n)}</span><i class="f1"></i><i class="f2"></i><i class="f3"></i></a>`).join('')}</div></div><ol class="twlist">${rows.map((p, i) => `<li><span>${i + 1}</span><a href="player-${slug(p.k)}.html">${esc(p.n)}</a><em>${p.gp ? (p[key] / p.gp).toFixed(2) + ' per game · ' + p.gp + ' games' : ''}</em><b>${typeof p[key] === 'number' && p[key] % 1 ? p[key].toFixed(1) : p[key]}${unit}</b></li>`).join('')}</ol>`); };
export const race = () => { const data = { goals: leaders.goals, assists: leaders.assists, rating: leaders.rating, mom: leaders.mom }; const R = Object.fromEntries(Object.entries(data).map(([k, a]) => [k, a.slice(0, 6).map((p) => ({ n: p.n, v: k === 'rating' ? +p.rating.toFixed(1) : p[k], s: k === 'rating' ? `${p.gp} games` : p.gp ? `${(p[k] / p.gp).toFixed(2)}/game` : '' }))])); return wx('', `<div class="chips" data-w="racetabs"><button class="chip on" data-k="goals">Goals</button><button class="chip" data-k="assists">Assists</button><button class="chip" data-k="rating">Rating</button><button class="chip" data-k="mom">MOTM</button></div><div class="race" data-w="race" data-j="${J(R)}"></div>`); };
const AX = [['Goals / game', (p) => p.goals / Math.max(1, p.gp)], ['Assists / game', (p) => p.assists / Math.max(1, p.gp)], ['Rating', (p) => p.rating], ['Passing', (p) => p.pass], ['Tackling', (p) => p.tackleRate], ['Win rate', (p) => p.win]];
export const radar = (list = T.slice().sort((a, b) => b.rating - a.rating).slice(0, 3)) => { const mx = AX.map(([, f]) => Math.max(1e-9, ...T.map(f))); return wx('', `<div class="radar" data-w="radar" data-j="${J({ axes: AX.map((a) => a[0]), series: list.map((p) => ({ n: p.n, v: AX.map(([, f], i) => +(f(p) / mx[i]).toFixed(3)) })) })}"></div>`); };
export const formWave = (ms = recent) => { const c = (r) => ms.filter((m) => m.res === r).length, gf = ms.reduce((a, m) => a + m.gf, 0), ga = ms.reduce((a, m) => a + m.ga, 0), pts = ms.reduce((a, m) => a + (m.res === 'W' ? 3 : m.res === 'D' ? 1 : 0), 0);
  return wx('', `<div data-w="form" data-j="${J(ms.map((m) => ({ opp: m.opp, gf: m.gf, ga: m.ga, res: m.res, d: fmtDate(m.t), id: m.id })).reverse())}"><div class="formrow"></div><svg class="wave" viewBox="0 0 600 120" preserveAspectRatio="none"></svg><div class="fcap"><span>older</span><i>goal difference per game · above the line is a win</i><span>latest</span></div></div>
<div class="fsum"><span><b>${c('W')}</b>W</span><span><b>${c('D')}</b>D</span><span><b>${c('L')}</b>L</span><span><b>${gf}–${ga}</b>goals</span><span><b>${Math.round(pts / Math.max(1, ms.length * 3) * 100)}%</b>of points</span></div><ul class="fres">${ms.slice(0, 5).map((m) => `<li><a href="match-${m.id}.html"><i class="${m.res}">${m.res}</i><span>${oppCrest(m.crest, m.opp, 22)} ${esc(m.opp)} ${tagChips(m, 2)}</span><em>${esc(fmtDate(m.t))}</em><b>${m.gf}–${m.ga}</b></a></li>`).join('')}</ul>`); };

// ---- rails ----
export const coverflow = (list = byOvr.slice(0, 12)) => wx('', `<div class="rail cover" data-w="cover">${list.map((p) => `<div class="ci">${card(p, { s: .9 })}</div>`).join('')}</div>`);
export const deck = (list = byOvr.slice(0, 6)) => wx('', `<div class="deck" data-w="deck">${list.map((p) => `<div class="dk">${card(p, { s: .95, link: false })}</div>`).join('')}</div><p class="hint">Tap the top card</p>`);
export const flipcards = (list = byOvr.slice(0, 3)) => wx('', `<div class="flipwrap">${list.map((p) => `<button class="flip" type="button" aria-label="Flip ${esc(p.n)}"><span class="f"><span class="ft">${card(p, { s: .8, link: false })}</span><span class="bk"><b>${esc(p.n)}</b><em>${esc(p.arch)}</em><i><u>${p.goals}</u>Goals</i><i><u>${p.assists}</u>Assists</i><i><u>${p.rating.toFixed(1)}</u>Rating</i><i><u>${p.mom}</u>MOTM</i></span></span></button>`).join('')}</div>`);
const mdet = (m) => { const L = m.lines || [], mo = L.filter((l) => l.mom).map((l) => l.n), sc = L.filter((l) => l.goals).map((l) => `${l.n} ${l.goals > 1 ? '×' + l.goals : ''}`.trim()), top = L.filter((l) => l.rating).sort((a, b) => b.rating - a.rating)[0]; return [mo.length ? 'MOTM ' + mo.join(', ') : top ? `Top rated ${top.n} ${top.rating}` : '', sc.length ? 'Scorers ' + sc.join(', ') : (m.gf ? '' : 'No goals for us')].filter(Boolean).join(' · '); };
export const timeline = (ms = recent) => wx('', `<div class="rail tl" data-w="tl"><div class="line"></div>${ms.slice().reverse().map((m, i) => `<button class="dot ${m.res}" data-i="${i}" data-h="match-${m.id}.html" data-t="${esc(`${fmtDate(m.t)} · ${m.gf}–${m.ga} vs ${m.opp}`)}" data-d="${esc(mdet(m))}"><span class="pt"></span><span class="lbl">${esc(m.opp.length > 11 ? m.opp.slice(0, 10) + '…' : m.opp)}<small>${fmtDate(m.t)}</small></span></button>`).join('')}</div><a class="tlo" id="tlo" href="${ms[0] ? `match-${ms[0].id}.html` : 'results.html'}">${ms[0] ? esc(`${fmtDate(ms[0].t)} · ${ms[0].gf}–${ms[0].ga} vs ${ms[0].opp}`) + ' · open' : 'Tap a game'}</a><p class="tdet" id="tdet">${esc(ms[0] ? mdet(ms[0]) : '')}</p>${(() => { const b = records.biggestWin, c = ms.filter((m) => m.res === 'W').length; const mx = Math.max(1, ...ms.map((m) => Math.max(m.gf, m.ga))); return `<div class="tbars" role="img" aria-label="Goals for and against in each game">${ms.slice().reverse().map((m) => `<span title="${esc(m.opp)} ${m.gf}-${m.ga}"><i class="f" style="height:${Math.max(3, m.gf / mx * 54)}px"></i><i class="a" style="height:${Math.max(3, m.ga / mx * 54)}px"></i></span>`).join('')}</div><p class="tcap">Goals for <b class="gf">■</b> and against <b class="ga">■</b> in each of these games, oldest to newest</p><div class="fsum tsum"><span><b>${c}–${ms.filter((m) => m.res === 'D').length}–${ms.filter((m) => m.res === 'L').length}</b>W–D–L here</span>${b ? `<span><b>${b.gf}–${b.ga}</b>biggest win · ${esc(b.opp.length > 12 ? b.opp.slice(0, 11) + '…' : b.opp)}</span>` : ''}<span><b>${ms.reduce((a, m) => a + m.gf, 0)}</b>goals scored</span></div>`; })()}`);

// ---- tables ----
const mxv = (arr, f) => Math.max(1e-9, ...arr.map(f));
export const glassTable = (arr, key, fmt = (v) => v, sub = (p) => `${p.arch} · ${p.line}`) => { const m = mxv(arr, (p) => p[key]); return wx('', `<div class="tbl glass">${arr.map((p, i) => `<a class="tr" href="player-${slug(p.k)}.html" style="--i:${i}"><span class="rk r${i + 1}">${i + 1}</span><span class="nm"><b>${esc(p.n)}</b><em>${esc(sub(p))}</em></span><span class="bar"><i style="--w:${(p[key] / m * 100).toFixed(0)}%"></i></span><b class="v">${fmt(p[key])}</b><span class="pill2">${p.rating ? p.rating.toFixed(1) : '—'}</span></a>`).join('')}</div>`); };
const heat = (v, m) => `background:rgba(200,53,44,${(0.08 + 0.5 * v / m).toFixed(2)})`;
export const heatTable = (arr) => wx('', `<div class="hscroll"><table class="heat"><thead><tr><th>Player</th><th>GP</th><th>Goals</th><th>Assists</th><th>Rating</th><th>MOTM</th><th>Pass %</th><th>Win %</th></tr></thead><tbody>${arr.map((p) => `<tr><th><a href="player-${slug(p.k)}.html">${esc(p.n)}</a></th><td style="${heat(p.gp, mxv(arr, (x) => x.gp))}">${p.gp}</td><td style="${heat(p.goals, mxv(arr, (x) => x.goals))}">${p.goals}</td><td style="${heat(p.assists, mxv(arr, (x) => x.assists))}">${p.assists}</td><td style="${heat(p.rating, 10)}">${p.rating.toFixed(1)}</td><td style="${heat(p.mom, mxv(arr, (x) => x.mom))}">${p.mom}</td><td style="${heat(p.pass, 100)}">${p.pass}</td><td style="${heat(p.win, 100)}">${p.win}</td></tr>`).join('')}</tbody></table></div>`);
export const podium = (arr, key, lab = 'goals', mini = true) => wx('', `<div class="podium">${[1, 0, 2].map((i) => { const x = arr[i]; return x ? `<a class="pd p${i + 1}" href="player-${slug(x.k)}.html"><div class="who"><b>${esc(x.n.length > 11 ? x.n.slice(0, 10) + '…' : x.n)}</b><em>${typeof x[key] === 'number' && x[key] % 1 ? x[key].toFixed(1) : x[key]} ${lab}</em></div><div class="blk"><span>${i + 1}</span></div></a>` : ''; }).join('')}</div>${!mini ? '' : `<div class="tbl glass mini">${arr.slice(3, 8).map((x, i) => `<a class="tr" href="player-${slug(x.k)}.html"><span class="rk">${i + 4}</span><span class="nm"><b>${esc(x.n)}</b></span><b class="v">${typeof x[key] === 'number' && x[key] % 1 ? x[key].toFixed(1) : x[key]}</b></a>`).join('')}</div>`}`);
export const expRows = (arr) => wx('', `<div class="tbl xp">${arr.map((x) => `<div class="xr"><button class="tr" type="button"><span class="nm"><b>${esc(x.n)}</b><em>${esc(x.arch)} · ${x.line}</em></span><b class="v">${x.ovr ?? '—'}</b><i class="chev">⌄</i></button><div class="xd"><div><u>Goals</u><b>${x.goals}</b></div><div><u>Assists</u><b>${x.assists}</b></div><div><u>Rating</u><b>${x.rating.toFixed(1)}</b></div><div><u>MOTM</u><b>${x.mom}</b></div><div><u>Win %</u><b>${x.win}</b></div><a class="chip gold" href="player-${slug(x.k)}.html" style="grid-column:1/-1;justify-self:center">Open profile →</a></div></div>`).join('')}</div>`);
export const ledger = (ms = recent) => wx('', `<div class="tbl led">${ms.map((m) => `<a class="tr ${m.res}" href="match-${m.id}.html"><span class="dt">${fmtDate(m.t)}</span><span class="nm">${oppCrest(m.crest, m.opp, 24)} <b>${esc(m.opp)}</b> ${tagChips(m, 3)}</span><span class="sc2">${m.gf}–${m.ga}</span><span class="rs">${m.res}</span></a>`).join('')}</div>`);

// ---- trophies ----
let cupN = 0;
const cup = (label, val, dim) => { const id = 'c' + ++cupN; return `<div class="cab${dim ? ' dim' : ''}"><svg viewBox="0 0 100 120" class="cup" aria-hidden="true"><defs><linearGradient id="cg${id}" x1="0" x2="1"><stop offset="0" stop-color="#a77a22"/><stop offset=".45" stop-color="#fff1c2"/><stop offset="1" stop-color="#c9993a"/></linearGradient><clipPath id="cc${id}"><path d="M25 10h50v30c0 20-12 32-25 34-13-2-25-14-25-34z"/><rect x="45" y="74" width="10" height="18"/><rect x="30" y="92" width="40" height="10" rx="3"/><rect x="24" y="102" width="52" height="12" rx="3"/></clipPath></defs><path d="M25 18H10c0 18 8 28 18 30M75 18h15c0 18-8 28-18 30" fill="none" stroke="url(#cg${id})" stroke-width="5" stroke-linecap="round"/><g fill="url(#cg${id})"><path d="M25 10h50v30c0 20-12 32-25 34-13-2-25-14-25-34z"/><rect x="45" y="74" width="10" height="18"/><rect x="30" y="92" width="40" height="10" rx="3"/><rect x="24" y="102" width="52" height="12" rx="3"/></g><g clip-path="url(#cc${id})"><rect class="shine" x="-40" y="0" width="30" height="130" fill="#fff" opacity=".55" transform="skewX(-20)"/></g></svg><b>${val}</b><u>${label}</u></div>`; };
export const cabinet = () => wx('', `<div class="cabinet">${cup('Division', 'Div ' + (C.div || 1))}${cup('Best win run', bestRun())}${cup('Goals scored', C.gf)}${cup('Promotions', C.promotions ?? 0)}${cup('Skill rating', C.sr)}${cup('Next: Elite division', '?', 1)}</div>`);
export const AW = () => [['Golden Boot', '⚽', best((x) => x.goals), (x) => x.goals + ' goals'], ['Playmaker', '🅰️', best((x) => x.assists), (x) => x.assists + ' assists'], ['Top rated', '⭐', best((x) => x.rating), (x) => x.rating.toFixed(1) + ' avg'], ['Man of the match', '🏅', best((x) => x.mom), (x) => x.mom + ' MOTM'], ['The Wall', '🧤', best((x) => x.cs), (x) => x.cs + ' clean sheets'], ['Iron man', '⏱️', best((x) => x.gp), (x) => x.gp + ' games']];
export const medals = () => wx('', `<div class="medals">${AW().map(([t, i, x, f], k) => `<a class="md" href="player-${slug(x.k)}.html" style="--i:${k}"><svg viewBox="0 0 80 100"><path d="M22 0l14 38h8L58 0z" fill="#c8352c"/><path d="M30 0l9 26 9-26z" fill="#fff" opacity=".85"/><circle cx="40" cy="64" r="28" fill="url(#mg)" stroke="#fff1c2" stroke-width="2"/><circle cx="40" cy="64" r="21" fill="none" stroke="#7a5614" stroke-width="1.5" stroke-dasharray="2 3"/><text x="40" y="73" text-anchor="middle" font-size="24">${i}</text></svg><b>${t}</b><em>${esc(x.n)}</em><u>${f(x)}</u></a>`).join('')}<svg width="0" height="0"><defs><radialGradient id="mg" cx=".35" cy=".3"><stop offset="0" stop-color="#fff1c2"/><stop offset=".6" stop-color="#e0b04a"/><stop offset="1" stop-color="#8a6212"/></radialGradient></defs></svg></div>`);
export const poster = (p = best((x) => x.rating)) => wx('', `<div class="poster"><div class="rays"></div><div class="pt"><span>PLAYER OF THE MONTH</span>${card(p, { s: .78 })}<b>${esc(p.n)}</b><em>${p.rating.toFixed(1)} average · ${p.goals} goals · ${p.assists} assists</em></div></div>`);
export const tiers = (lvl = -1) => wx('', `<div class="tiers">${[['Bronze', '#b0703c', '#5a3416'], ['Silver', '#cfd6e2', '#5e6779'], ['Gold', '#efcf7a', '#8a6212'], ['Elite', '#6ee7ff', '#1b5a74']].map(([n, a, b], i) => `<div class="tr2${lvl >= 0 && i !== lvl ? ' off' : ''}" style="--i:${i}"><svg viewBox="0 0 60 70"><defs><linearGradient id="t${i}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><path d="M30 3l24 8v22c0 17-11 28-24 33C17 61 6 50 6 33V11z" fill="url(#t${i})" stroke="#fff" stroke-opacity=".5" stroke-width="1.5"/><text x="30" y="42" text-anchor="middle" font-family="Oswald" font-weight="700" font-size="24" fill="#fff" stroke="rgba(0,0,0,.35)" stroke-width="2" style="paint-order:stroke">${i + 1}</text></svg><b>${n}</b></div>`).join('')}</div>`);
// rating tier from card overall: <75 bronze, <80 silver, <85 gold, else elite
export const tierOf = (ovr) => (ovr >= 85 ? 3 : ovr >= 80 ? 2 : ovr >= 75 ? 1 : 0);

// ---- match reel: result cards on a cover-flow, grouped into match nights (chips) ----
const CREST = 'https://eafc24.content.easports.com/fifa/fltOnlineAssets/24B23FDE-7835-41C2-87A2-F453DFDB2E82/2024/fcweb/crests/256x256/l';
const dayKey = (t) => new Date(t * 1000).toISOString().slice(0, 10);
const dayLab = (t) => new Date(t * 1000).toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', timeZone: 'UTC' }).toUpperCase().replace(',', '');
const typeLab = (t) => ({ leagueMatch: 'League', playoffMatch: 'Playoff', friendlyMatch: 'Friendly' })[t] || 'Match';
const oppBadge = (m) => m.crest ? `<img src="${CREST}${esc(m.crest)}.png" alt="" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('span'),{className:'ob',textContent:'${esc((m.opp[0] || '?').toUpperCase())}'}))">` : `<span class="ob">${esc((m.opp[0] || '?').toUpperCase())}</span>`;
export const reel = (ms = matches.slice(0, 10)) => {
  const list = ms.slice().reverse(), days = [];
  list.forEach((m, i) => { const k = dayKey(m.t); let g = days.find((x) => x.k === k); if (!g) days.push(g = { k, t: m.t, first: i, w: 0, l: 0, d: 0 }); g[m.res.toLowerCase()]++; });
  const chips = days.map((g) => `<button class="rchip" type="button" data-i="${g.first}">${ic('calendar', 14)}${dayLab(g.t)} · ${[g.w && g.w + 'W', g.d && g.d + 'D', g.l && g.l + 'L'].filter(Boolean).join(' ')}</button>`).join('');
  const cards = list.map((m, i) => { const sc = m.lines.filter((l) => l.goals).map((l) => `${esc(l.n)}${l.goals > 1 ? ' ×' + l.goals : ''}`), mo = m.lines.find((l) => l.mom) || m.lines.slice().sort((a, b) => b.rating - a.rating)[0];
    return `<div class="ci"><a class="rcard ${m.res}" href="match-${m.id}.html" data-i="${i}"><div class="rtop"><span>${ic('trophy', 14)} ${typeLab(m.type)} · ${esc(new Date(m.t * 1000).toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short', timeZone: 'UTC' }).replace(',', '').toUpperCase())}</span><b class="rbadge">${{ W: 'VICTORY', D: 'DRAW', L: 'DEFEAT' }[m.res]}</b></div>
<div class="rmid"><div class="rc-t"><img src="crest.png" alt=""><span>NOREX UNITED FC</span></div><div class="rc-s"><b>${m.gf}</b><i>:</i><b>${m.ga}</b></div><div class="rc-t"><div class="oc">${oppBadge(m)}</div><span>${esc(m.opp)}</span>${sc.length ? `<small>⚽ ${sc.slice(0, 3).join(', ')}</small>` : '<small>⚽ no goals for us</small>'}</div></div>
<div class="rtags">${tagChips(m, 4)}</div>${mo ? `<div class="rmo">⭐ <span>${m.lines.some((l) => l.mom) ? 'Man of the match' : 'Top rated'}</span> <b>${esc(mo.n)}</b><em>${mo.rating ? (+mo.rating).toFixed(1) : ''}</em></div>` : ''}</a></div>`; }).join('');
  return wx('', `<div class="reelwrap"><div class="rchips">${chips}</div><div class="rail cover reel" data-w="reel">${cards}</div><div class="rnav"><button class="rn" type="button" data-d="-1" aria-label="Previous match">${ic('left', 16)}</button><span class="rhint">Drag the reel · match <b>${list.length}</b> of ${list.length}</span><button class="rn" type="button" data-d="1" aria-label="Next match">${ic('right', 16)}</button><a class="rcal" href="fixtures.html">${ic('calendar', 15)} Calendar</a></div></div>`);
};

// ---- KPI deck: every club number, each shown in the form that suits it (ladder, record bar, mosaic, balance, dials, equaliser) ----
const arc = (v, max, r = 30) => { const c = 2 * Math.PI * r, k = Math.max(0, Math.min(1, v / max)); return `stroke-dasharray:${(c * k).toFixed(1)} ${c.toFixed(1)}`; };
export const kpi = () => {
  const gp = Math.max(1, C.gp), wr = Math.round(C.w / gp * 100), gdv = C.gf - C.ga, ppg = (3 * C.w + C.d) / gp, [rn, rl] = runNow(), tr = pointsTrend(), sp = sparkPath(tr);
  const old = matches.slice().reverse(), last10 = matches.slice(0, 10).reverse(), sh = matches.filter((m) => m.ga === 0).length;
  const div = Math.max(1, Math.min(10, C.div || 1));
  const ladder = Array.from({ length: 10 }, (_, i) => { const d = 10 - i; return `<i class="${d >= div ? 'on' : ''}${d === div ? ' cur' : ''}" title="Division ${d}"></i>`; }).join('');
  const tot = C.w + C.d + C.l || 1, pc = (v) => (v / tot * 100).toFixed(2);
  const forPct = (C.gf / Math.max(1, C.gf + C.ga) * 100).toFixed(1);
  const dial = (v, max, label, sub, col, emo, dp = 1) => `<div class="kc dial"><svg viewBox="0 0 80 80" aria-hidden="true"><circle cx="40" cy="40" r="30" class="bg"/><circle cx="40" cy="40" r="30" class="fg" style="${arc(v, max)};stroke:${col}"/></svg><div class="dv"><b class="cnt" data-n="${v}" data-d="${dp}">0</b><u>${emo} ${label}</u></div><small>${sub}</small></div>`;
  return wx('', `<div class="kpi">
<div class="kc k-rate"><u>💎 Skill rating</u><b class="cnt" data-n="${C.sr}">0</b><div class="ladder" aria-label="Division ${div} of 10">${ladder}<span>Division ${div}</span></div><small>${C.promotions ?? 0} promotion${C.promotions === 1 ? '' : 's'} · ${C.pts ?? 0} pts</small><svg class="sp" viewBox="0 0 100 24" preserveAspectRatio="none" aria-hidden="true"><path d="${sp.line}" class="spark"/><circle cx="${sp.end[0].toFixed(1)}" cy="${sp.end[1].toFixed(1)}" r="1.6" class="sdot"/></svg><i class="cap">League points · last ${tr.length} games</i></div>
<div class="kc k-rec"><div class="kh"><u>🎮 Season record</u><span><b class="cnt" data-n="${C.gp}">0</b> played</span></div>
<div class="rbar" role="img" aria-label="${C.w} wins, ${C.d} draws, ${C.l} losses"><i class="w" style="flex:${C.w}"><b>${C.w}</b></i><i class="d" style="flex:${Math.max(C.d, .001)}"><b>${C.d}</b></i><i class="l" style="flex:${Math.max(C.l, .001)}"><b>${C.l}</b></i></div>
<div class="rleg"><span class="w">🏆 ${C.w} wins · ${pc(C.w)}%</span><span class="d">🤝 ${C.d} draws</span><span class="l">💔 ${C.l} losses</span></div>
<div class="mosaic" role="img" aria-label="Result of each of the last ${old.length} games, oldest first">${old.map((m, i) => `<a href="match-${m.id}.html" class="${m.res}${m.ga === 0 ? ' cs' : ''}" style="--i:${i}" title="${esc(m.opp)} ${m.gf}–${m.ga}"></a>`).join('')}</div>
<i class="cap">Every game as a tile, oldest to newest · a dot marks a clean sheet</i></div>
<div class="kc k-bal"><div class="kh"><u>⚽ Goals for and against</u><span class="gdv">${gdv >= 0 ? '+' : ''}${gdv}</span></div>
<div class="tug" role="img" aria-label="${C.gf} scored, ${C.ga} conceded"><i class="f" style="width:${forPct}%"><b class="cnt" data-n="${C.gf}">0</b></i><i class="a" style="width:${(100 - forPct).toFixed(1)}%"><b class="cnt" data-n="${C.ga}">0</b></i></div>
<div class="rleg"><span class="w">scored · ${(C.gf / gp).toFixed(1)} a game</span><span class="l">conceded · ${(C.ga / gp).toFixed(1)} a game</span></div></div>
<div class="kc dial k-win"><svg viewBox="0 0 80 80" aria-hidden="true"><circle cx="40" cy="40" r="30" class="bg"/><circle cx="40" cy="40" r="30" class="fg" style="${arc(C.w, tot)};stroke:#2ecb78"/></svg><div class="dv"><b>${wr}%</b><u>📈 Win rate</u></div><small>${C.w} of ${C.gp} games won</small></div>
${dial(+(C.gf / gp).toFixed(1), 5, 'Goals / game', `of ${C.gf} scored`, '#efcf7a', '⚽')}
${dial(+(C.ga / gp).toFixed(1), 5, 'Conceded / game', `${sh} clean sheets in last ${matches.length}`, '#6ac7ff', '🧤')}
${dial(+ppg.toFixed(2), 3, 'Points / game', `of a possible 3`, '#c8352c', '🔥', 2)}
<div class="kc k-run"><div class="kh"><u>🔥 Current run</u><span><b class="cnt" data-n="${typeof rn === 'number' ? rn : 0}">0</b> ${esc(rl)}</span></div><div class="eq" role="img" aria-label="Points from each of the last 10 games">${last10.map((m, i) => `<i class="${m.res}" style="--h:${m.res === 'W' ? 100 : m.res === 'D' ? 45 : 16}%;--i:${i}" title="${esc(m.opp)} ${m.gf}–${m.ga}"></i>`).join('')}</div><small>Last 10 games · tall bar = win</small></div>
</div><p class="wnote">Live from EA's club data · updated ${esc(fmtDate(Math.floor(Date.parse(C.fetched) / 1000)))} · ${C.gp} league games</p>`);
};

// ---- calendar heat map: one cell per day, shaded by games played, tinted by how the day went ----
export const calendar = () => {
  const DAY = 86400, day = (t) => Math.floor(t / DAY), by = new Map(), span = Math.ceil((day(matches[0]?.t ?? 0) - day(matches[matches.length - 1]?.t ?? 0)) / 7) + 1, weeks = Math.max(4, Math.min(14, span));
  for (const m of matches) { const k = day(m.t), a = by.get(k) ?? []; a.push(m); by.set(k, a); }
  const last = day(matches[0]?.t ?? 0), dow = (k) => (new Date(k * DAY * 1000).getUTCDay() + 6) % 7; // Monday = 0
  const end = last + (6 - dow(last)), start = end - weeks * 7 + 1, cols = [];
  for (let k = start; k <= end; k += 7) cols.push(Array.from({ length: 7 }, (_, i) => k + i));
  const cell = (k) => { const g = by.get(k) || []; const wn = g.filter((m) => m.res === 'W').length, ls = g.filter((m) => m.res === 'L').length; const tone = !g.length ? '' : wn > ls ? 'w' : ls > wn ? 'l' : 'd'; const lv = Math.min(4, g.length);
    const lab = new Date(k * DAY * 1000).toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short', timeZone: 'UTC' });
    return `<i class="${tone} lv${lv}" title="${esc(lab)}${g.length ? ' · ' + g.map((m) => `${m.res} ${m.gf}–${m.ga} ${esc(m.opp)}`).join(', ') : ' · no games'}"${g.length ? ` data-h="match-${g[0].id}.html"` : ''}></i>`; };
  const months = cols.map((c, i) => { const d = new Date(c[0] * DAY * 1000), prev = i ? new Date(cols[i - 1][0] * DAY * 1000) : null; return !prev || prev.getUTCMonth() !== d.getUTCMonth() ? d.toLocaleDateString('en-GB', { month: 'short', timeZone: 'UTC' }) : ''; });
  const total = matches.filter((m) => day(m.t) >= start).length, busiest = [...by.entries()].filter(([k]) => k >= start).sort((a, b) => b[1].length - a[1].length)[0];
  return wx('', `<div class="cal"><div class="calgrid"><div class="cdays"><span>Mon</span><span></span><span>Wed</span><span></span><span>Fri</span><span></span><span>Sun</span></div>${cols.map((c, i) => `<div class="ccol"><b>${months[i]}</b>${c.map(cell).join('')}</div>`).join('')}</div>
<div class="cleg"><span><i class="w lv3"></i> good day</span><span><i class="d lv3"></i> level</span><span><i class="l lv3"></i> tough day</span><span class="muted">darker = more games</span></div>
<p class="wnote">${total} games in the last ${weeks} weeks${busiest ? ` · busiest day ${busiest[1].length} games (${esc(new Date(busiest[0] * DAY * 1000).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', timeZone: 'UTC' }))})` : ''}</p></div>`);
};

// ---- rating spread: every match rating as a dot on a 5–10 track, the average as a tick ----
export const ratingSpread = (n = 10) => {
  const rows = players.filter((p) => p.gp >= 5).map((p) => ({ p, r: matches.flatMap((m) => m.lines.filter((l) => l.n === p.n && l.rating).map((l) => l.rating)) })).filter((x) => x.r.length >= 4).sort((a, b) => b.p.rating - a.p.rating).slice(0, n);
  const x = (v) => Math.max(0, Math.min(100, (v - 5) / 5 * 100));
  return wx('', `<div class="spread"><div class="sax"><span></span><div class="ax"><i>5</i><i>6</i><i>7</i><i>8</i><i>9</i><i>10</i></div><span></span></div>${rows.map(({ p, r }) => { const avg = r.reduce((a, b) => a + b, 0) / r.length, lo = Math.min(...r), hi = Math.max(...r);
    return `<a class="srow" href="player-${slug(p.k)}.html"><span class="sn">${esc(p.n)}<small>${r.length} rated games</small></span><span class="strack"><i class="band" style="left:${x(lo)}%;width:${Math.max(1, x(hi) - x(lo))}%"></i>${r.map((v) => `<b style="left:${x(v)}%" title="${v}"></b>`).join('')}<em style="left:${x(avg)}%"></em></span><span class="sv">${avg.toFixed(1)}<small>${lo}–${hi}</small></span></a>`; }).join('')}</div><p class="wnote">Each dot is one match rating · the gold tick is the average · the faint band runs from the worst to the best game</p>`);
};

// ---- head-to-head ribbon: every meeting with an opponent, oldest to newest ----
export const h2h = (oppId) => `<span class="h2h">${matches.filter((m) => m.oppId === oppId).slice().reverse().map((m) => `<i class="${m.res}" title="${esc(fmtDate(m.t))} · ${m.gf}–${m.ga}"></i>`).join('')}</span>`;
