const form=document.querySelector("#composer"),input=document.querySelector("#prompt"),stream=document.querySelector("#stream"),artifact=document.querySelector("#artifact"),tabs=[...document.querySelectorAll(".artifact-tab")];
const views={
 diff:{label:"GIT DIFF",status:"SHADOW",body:"No production diff loaded. Artifact service will render scoped patches here.",meta:".norex/** only"},
 tests:{label:"DETERMINISTIC TESTS",status:"READY",body:"Validation target: node tests/run.mjs",meta:"Targeted → shared regression → full suite"},
 terminal:{label:"TERMINAL",status:"GATED",body:"PTY service contract exists. Command execution is disabled in this browser-only shell.",meta:"Approval + scoped local service required"},
 preview:{label:"BROWSER / PREVIEW",status:"GATED",body:"On-demand preview will appear here without turning Norex into a permanent browser.",meta:"MFA/CAPTCHA remain human checkpoints"}
};
function showArtifact(name){tabs.forEach(t=>t.classList.toggle("active",t.dataset.artifact===name));if(name==="session"){artifact.hidden=true;stream.hidden=false;return}const v=views[name];stream.hidden=true;artifact.hidden=false;artifact.replaceChildren();const head=document.createElement("div");head.className="artifact-head";const title=document.createElement("div");title.innerHTML="<small>"+v.label+"</small><h3>"+v.status+"</h3>";const badge=document.createElement("span");badge.className="artifact-state";badge.textContent=name==="tests"?"LOCAL":"POLICY";head.append(title,badge);const body=document.createElement("pre");body.textContent=v.body;const meta=document.createElement("p");meta.className="artifact-meta";meta.textContent=v.meta;artifact.append(head,body,meta)}
tabs.forEach(t=>t.addEventListener("click",()=>showArtifact(t.dataset.artifact)));
form.addEventListener("submit",e=>{e.preventDefault();const value=input.value.trim();if(!value)return;showArtifact("session");const card=document.createElement("article");card.className="event mike";const label=document.createElement("small");label.textContent="MIKE";const p=document.createElement("p");p.textContent=value;card.append(label,p);stream.append(card);input.value="";stream.scrollTop=stream.scrollHeight;});
input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,160)+"px"});
